/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PatientsRouteImport } from './routes/patients'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliesIndexRouteImport } from './routes/supplies.index'
import { Route as LabsIndexRouteImport } from './routes/labs.index'
import { Route as ImplantsIndexRouteImport } from './routes/implants.index'
import { Route as ProfileAccountIdRouteImport } from './routes/profile.$accountId'
import { Route as LabsExploreRouteImport } from './routes/labs.explore'
import { Route as LabsDashboardRouteImport } from './routes/labs.dashboard'
import { Route as LabsCasesRouteImport } from './routes/labs.cases'
import { Route as LabsLabIdRouteImport } from './routes/labs.$labId'
import { Route as ImplantsCountryRouteImport } from './routes/implants.$country'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AccountHelpRouteImport } from './routes/account.help'
import { Route as AccountBalancesRouteImport } from './routes/account.balances'
import { Route as AccountAboutRouteImport } from './routes/account.about'
import { Route as SuppliesOfficeIdIndexRouteImport } from './routes/supplies.$officeId.index'
import { Route as SuppliesBranchBranchSlugRouteImport } from './routes/supplies.branch.$branchSlug'
import { Route as SuppliesOfficeIdBranchSlugRouteImport } from './routes/supplies.$officeId.$branchSlug'
import { Route as LabsLabIdStatementRouteImport } from './routes/labs.$labId.statement'
import { Route as AccountHelpTopicSlugRouteImport } from './routes/account.help.topic.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsRoute = PatientsRouteImport.update({
  id: '/patients',
  path: '/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliesIndexRoute = SuppliesIndexRouteImport.update({
  id: '/supplies/',
  path: '/supplies/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsIndexRoute = LabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantsIndexRoute = ImplantsIndexRouteImport.update({
  id: '/implants/',
  path: '/implants/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileAccountIdRoute = ProfileAccountIdRouteImport.update({
  id: '/profile/$accountId',
  path: '/profile/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsExploreRoute = LabsExploreRouteImport.update({
  id: '/labs/explore',
  path: '/labs/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsDashboardRoute = LabsDashboardRouteImport.update({
  id: '/labs/dashboard',
  path: '/labs/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsCasesRoute = LabsCasesRouteImport.update({
  id: '/labs/cases',
  path: '/labs/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsLabIdRoute = LabsLabIdRouteImport.update({
  id: '/labs/$labId',
  path: '/labs/$labId',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantsCountryRoute = ImplantsCountryRouteImport.update({
  id: '/implants/$country',
  path: '/implants/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountHelpRoute = AccountHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AccountRoute,
} as any)
const AccountBalancesRoute = AccountBalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAboutRoute = AccountAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AccountRoute,
} as any)
const SuppliesOfficeIdIndexRoute = SuppliesOfficeIdIndexRouteImport.update({
  id: '/supplies/$officeId/',
  path: '/supplies/$officeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliesBranchBranchSlugRoute =
  SuppliesBranchBranchSlugRouteImport.update({
    id: '/supplies/branch/$branchSlug',
    path: '/supplies/branch/$branchSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuppliesOfficeIdBranchSlugRoute =
  SuppliesOfficeIdBranchSlugRouteImport.update({
    id: '/supplies/$officeId/$branchSlug',
    path: '/supplies/$officeId/$branchSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const LabsLabIdStatementRoute = LabsLabIdStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => LabsLabIdRoute,
} as any)
const AccountHelpTopicSlugRoute = AccountHelpTopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => AccountHelpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/doctors': typeof DoctorsRoute
  '/explore': typeof ExploreRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/orders': typeof OrdersRoute
  '/patients': typeof PatientsRoute
  '/pricing': typeof PricingRoute
  '/production': typeof ProductionRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/account/about': typeof AccountAboutRoute
  '/account/balances': typeof AccountBalancesRoute
  '/account/help': typeof AccountHelpRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/implants/$country': typeof ImplantsCountryRoute
  '/labs/$labId': typeof LabsLabIdRouteWithChildren
  '/labs/cases': typeof LabsCasesRoute
  '/labs/dashboard': typeof LabsDashboardRoute
  '/labs/explore': typeof LabsExploreRoute
  '/profile/$accountId': typeof ProfileAccountIdRoute
  '/implants/': typeof ImplantsIndexRoute
  '/labs/': typeof LabsIndexRoute
  '/supplies/': typeof SuppliesIndexRoute
  '/labs/$labId/statement': typeof LabsLabIdStatementRoute
  '/supplies/$officeId/$branchSlug': typeof SuppliesOfficeIdBranchSlugRoute
  '/supplies/branch/$branchSlug': typeof SuppliesBranchBranchSlugRoute
  '/supplies/$officeId/': typeof SuppliesOfficeIdIndexRoute
  '/account/help/topic/$slug': typeof AccountHelpTopicSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/doctors': typeof DoctorsRoute
  '/explore': typeof ExploreRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/orders': typeof OrdersRoute
  '/patients': typeof PatientsRoute
  '/pricing': typeof PricingRoute
  '/production': typeof ProductionRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/account/about': typeof AccountAboutRoute
  '/account/balances': typeof AccountBalancesRoute
  '/account/help': typeof AccountHelpRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/implants/$country': typeof ImplantsCountryRoute
  '/labs/$labId': typeof LabsLabIdRouteWithChildren
  '/labs/cases': typeof LabsCasesRoute
  '/labs/dashboard': typeof LabsDashboardRoute
  '/labs/explore': typeof LabsExploreRoute
  '/profile/$accountId': typeof ProfileAccountIdRoute
  '/implants': typeof ImplantsIndexRoute
  '/labs': typeof LabsIndexRoute
  '/supplies': typeof SuppliesIndexRoute
  '/labs/$labId/statement': typeof LabsLabIdStatementRoute
  '/supplies/$officeId/$branchSlug': typeof SuppliesOfficeIdBranchSlugRoute
  '/supplies/branch/$branchSlug': typeof SuppliesBranchBranchSlugRoute
  '/supplies/$officeId': typeof SuppliesOfficeIdIndexRoute
  '/account/help/topic/$slug': typeof AccountHelpTopicSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/doctors': typeof DoctorsRoute
  '/explore': typeof ExploreRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/orders': typeof OrdersRoute
  '/patients': typeof PatientsRoute
  '/pricing': typeof PricingRoute
  '/production': typeof ProductionRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/account/about': typeof AccountAboutRoute
  '/account/balances': typeof AccountBalancesRoute
  '/account/help': typeof AccountHelpRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/implants/$country': typeof ImplantsCountryRoute
  '/labs/$labId': typeof LabsLabIdRouteWithChildren
  '/labs/cases': typeof LabsCasesRoute
  '/labs/dashboard': typeof LabsDashboardRoute
  '/labs/explore': typeof LabsExploreRoute
  '/profile/$accountId': typeof ProfileAccountIdRoute
  '/implants/': typeof ImplantsIndexRoute
  '/labs/': typeof LabsIndexRoute
  '/supplies/': typeof SuppliesIndexRoute
  '/labs/$labId/statement': typeof LabsLabIdStatementRoute
  '/supplies/$officeId/$branchSlug': typeof SuppliesOfficeIdBranchSlugRoute
  '/supplies/branch/$branchSlug': typeof SuppliesBranchBranchSlugRoute
  '/supplies/$officeId/': typeof SuppliesOfficeIdIndexRoute
  '/account/help/topic/$slug': typeof AccountHelpTopicSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/doctors'
    | '/explore'
    | '/finance'
    | '/login'
    | '/messages'
    | '/more'
    | '/orders'
    | '/patients'
    | '/pricing'
    | '/production'
    | '/register'
    | '/reports'
    | '/signup'
    | '/account/about'
    | '/account/balances'
    | '/account/help'
    | '/account/settings'
    | '/implants/$country'
    | '/labs/$labId'
    | '/labs/cases'
    | '/labs/dashboard'
    | '/labs/explore'
    | '/profile/$accountId'
    | '/implants/'
    | '/labs/'
    | '/supplies/'
    | '/labs/$labId/statement'
    | '/supplies/$officeId/$branchSlug'
    | '/supplies/branch/$branchSlug'
    | '/supplies/$officeId/'
    | '/account/help/topic/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/doctors'
    | '/explore'
    | '/finance'
    | '/login'
    | '/messages'
    | '/more'
    | '/orders'
    | '/patients'
    | '/pricing'
    | '/production'
    | '/register'
    | '/reports'
    | '/signup'
    | '/account/about'
    | '/account/balances'
    | '/account/help'
    | '/account/settings'
    | '/implants/$country'
    | '/labs/$labId'
    | '/labs/cases'
    | '/labs/dashboard'
    | '/labs/explore'
    | '/profile/$accountId'
    | '/implants'
    | '/labs'
    | '/supplies'
    | '/labs/$labId/statement'
    | '/supplies/$officeId/$branchSlug'
    | '/supplies/branch/$branchSlug'
    | '/supplies/$officeId'
    | '/account/help/topic/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/doctors'
    | '/explore'
    | '/finance'
    | '/login'
    | '/messages'
    | '/more'
    | '/orders'
    | '/patients'
    | '/pricing'
    | '/production'
    | '/register'
    | '/reports'
    | '/signup'
    | '/account/about'
    | '/account/balances'
    | '/account/help'
    | '/account/settings'
    | '/implants/$country'
    | '/labs/$labId'
    | '/labs/cases'
    | '/labs/dashboard'
    | '/labs/explore'
    | '/profile/$accountId'
    | '/implants/'
    | '/labs/'
    | '/supplies/'
    | '/labs/$labId/statement'
    | '/supplies/$officeId/$branchSlug'
    | '/supplies/branch/$branchSlug'
    | '/supplies/$officeId/'
    | '/account/help/topic/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DoctorsRoute: typeof DoctorsRoute
  ExploreRoute: typeof ExploreRoute
  FinanceRoute: typeof FinanceRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  MoreRoute: typeof MoreRoute
  OrdersRoute: typeof OrdersRoute
  PatientsRoute: typeof PatientsRoute
  PricingRoute: typeof PricingRoute
  ProductionRoute: typeof ProductionRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SignupRoute: typeof SignupRoute
  ImplantsCountryRoute: typeof ImplantsCountryRoute
  LabsLabIdRoute: typeof LabsLabIdRouteWithChildren
  LabsCasesRoute: typeof LabsCasesRoute
  LabsDashboardRoute: typeof LabsDashboardRoute
  LabsExploreRoute: typeof LabsExploreRoute
  ProfileAccountIdRoute: typeof ProfileAccountIdRoute
  ImplantsIndexRoute: typeof ImplantsIndexRoute
  LabsIndexRoute: typeof LabsIndexRoute
  SuppliesIndexRoute: typeof SuppliesIndexRoute
  SuppliesOfficeIdBranchSlugRoute: typeof SuppliesOfficeIdBranchSlugRoute
  SuppliesBranchBranchSlugRoute: typeof SuppliesBranchBranchSlugRoute
  SuppliesOfficeIdIndexRoute: typeof SuppliesOfficeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients': {
      id: '/patients'
      path: '/patients'
      fullPath: '/patients'
      preLoaderRoute: typeof PatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplies/': {
      id: '/supplies/'
      path: '/supplies'
      fullPath: '/supplies/'
      preLoaderRoute: typeof SuppliesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/': {
      id: '/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof LabsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implants/': {
      id: '/implants/'
      path: '/implants'
      fullPath: '/implants/'
      preLoaderRoute: typeof ImplantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$accountId': {
      id: '/profile/$accountId'
      path: '/profile/$accountId'
      fullPath: '/profile/$accountId'
      preLoaderRoute: typeof ProfileAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/explore': {
      id: '/labs/explore'
      path: '/labs/explore'
      fullPath: '/labs/explore'
      preLoaderRoute: typeof LabsExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/dashboard': {
      id: '/labs/dashboard'
      path: '/labs/dashboard'
      fullPath: '/labs/dashboard'
      preLoaderRoute: typeof LabsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/cases': {
      id: '/labs/cases'
      path: '/labs/cases'
      fullPath: '/labs/cases'
      preLoaderRoute: typeof LabsCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/$labId': {
      id: '/labs/$labId'
      path: '/labs/$labId'
      fullPath: '/labs/$labId'
      preLoaderRoute: typeof LabsLabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implants/$country': {
      id: '/implants/$country'
      path: '/implants/$country'
      fullPath: '/implants/$country'
      preLoaderRoute: typeof ImplantsCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/help': {
      id: '/account/help'
      path: '/help'
      fullPath: '/account/help'
      preLoaderRoute: typeof AccountHelpRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/balances': {
      id: '/account/balances'
      path: '/balances'
      fullPath: '/account/balances'
      preLoaderRoute: typeof AccountBalancesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/about': {
      id: '/account/about'
      path: '/about'
      fullPath: '/account/about'
      preLoaderRoute: typeof AccountAboutRouteImport
      parentRoute: typeof AccountRoute
    }
    '/supplies/$officeId/': {
      id: '/supplies/$officeId/'
      path: '/supplies/$officeId'
      fullPath: '/supplies/$officeId/'
      preLoaderRoute: typeof SuppliesOfficeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplies/branch/$branchSlug': {
      id: '/supplies/branch/$branchSlug'
      path: '/supplies/branch/$branchSlug'
      fullPath: '/supplies/branch/$branchSlug'
      preLoaderRoute: typeof SuppliesBranchBranchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplies/$officeId/$branchSlug': {
      id: '/supplies/$officeId/$branchSlug'
      path: '/supplies/$officeId/$branchSlug'
      fullPath: '/supplies/$officeId/$branchSlug'
      preLoaderRoute: typeof SuppliesOfficeIdBranchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/$labId/statement': {
      id: '/labs/$labId/statement'
      path: '/statement'
      fullPath: '/labs/$labId/statement'
      preLoaderRoute: typeof LabsLabIdStatementRouteImport
      parentRoute: typeof LabsLabIdRoute
    }
    '/account/help/topic/$slug': {
      id: '/account/help/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/account/help/topic/$slug'
      preLoaderRoute: typeof AccountHelpTopicSlugRouteImport
      parentRoute: typeof AccountHelpRoute
    }
  }
}

interface AccountHelpRouteChildren {
  AccountHelpTopicSlugRoute: typeof AccountHelpTopicSlugRoute
}

const AccountHelpRouteChildren: AccountHelpRouteChildren = {
  AccountHelpTopicSlugRoute: AccountHelpTopicSlugRoute,
}

const AccountHelpRouteWithChildren = AccountHelpRoute._addFileChildren(
  AccountHelpRouteChildren,
)

interface AccountRouteChildren {
  AccountAboutRoute: typeof AccountAboutRoute
  AccountBalancesRoute: typeof AccountBalancesRoute
  AccountHelpRoute: typeof AccountHelpRouteWithChildren
  AccountSettingsRoute: typeof AccountSettingsRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAboutRoute: AccountAboutRoute,
  AccountBalancesRoute: AccountBalancesRoute,
  AccountHelpRoute: AccountHelpRouteWithChildren,
  AccountSettingsRoute: AccountSettingsRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface LabsLabIdRouteChildren {
  LabsLabIdStatementRoute: typeof LabsLabIdStatementRoute
}

const LabsLabIdRouteChildren: LabsLabIdRouteChildren = {
  LabsLabIdStatementRoute: LabsLabIdStatementRoute,
}

const LabsLabIdRouteWithChildren = LabsLabIdRoute._addFileChildren(
  LabsLabIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DoctorsRoute: DoctorsRoute,
  ExploreRoute: ExploreRoute,
  FinanceRoute: FinanceRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  MoreRoute: MoreRoute,
  OrdersRoute: OrdersRoute,
  PatientsRoute: PatientsRoute,
  PricingRoute: PricingRoute,
  ProductionRoute: ProductionRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SignupRoute: SignupRoute,
  ImplantsCountryRoute: ImplantsCountryRoute,
  LabsLabIdRoute: LabsLabIdRouteWithChildren,
  LabsCasesRoute: LabsCasesRoute,
  LabsDashboardRoute: LabsDashboardRoute,
  LabsExploreRoute: LabsExploreRoute,
  ProfileAccountIdRoute: ProfileAccountIdRoute,
  ImplantsIndexRoute: ImplantsIndexRoute,
  LabsIndexRoute: LabsIndexRoute,
  SuppliesIndexRoute: SuppliesIndexRoute,
  SuppliesOfficeIdBranchSlugRoute: SuppliesOfficeIdBranchSlugRoute,
  SuppliesBranchBranchSlugRoute: SuppliesBranchBranchSlugRoute,
  SuppliesOfficeIdIndexRoute: SuppliesOfficeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
