/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ReportsRouteImport } from './routes/reports'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as QuickOrdersRouteImport } from './routes/quick-orders'
import { Route as ProductionRouteImport } from './routes/production'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as OrdersRouteImport } from './routes/orders'
import { Route as OffersRouteImport } from './routes/offers'
import { Route as MyAdsRouteImport } from './routes/my-ads'
import { Route as MoreRouteImport } from './routes/more'
import { Route as MessagesRouteImport } from './routes/messages'
import { Route as LoginRouteImport } from './routes/login'
import { Route as FinanceRouteImport } from './routes/finance'
import { Route as ExploreRouteImport } from './routes/explore'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrackCasesIndexRouteImport } from './routes/track-cases.index'
import { Route as SurgicalGuideIndexRouteImport } from './routes/surgical-guide.index'
import { Route as SuppliesIndexRouteImport } from './routes/supplies.index'
import { Route as SpecializedImplantsIndexRouteImport } from './routes/specialized-implants.index'
import { Route as PatientsIndexRouteImport } from './routes/patients.index'
import { Route as LabsIndexRouteImport } from './routes/labs.index'
import { Route as InvoicesIndexRouteImport } from './routes/invoices.index'
import { Route as ImplantsIndexRouteImport } from './routes/implants.index'
import { Route as FavoritesIndexRouteImport } from './routes/favorites.index'
import { Route as DoctorInvoicesIndexRouteImport } from './routes/doctor-invoices.index'
import { Route as DesignerIndexRouteImport } from './routes/designer.index'
import { Route as ClinicIndexRouteImport } from './routes/clinic.index'
import { Route as BrandsIndexRouteImport } from './routes/brands.index'
import { Route as BoneGraftsIndexRouteImport } from './routes/bone-grafts.index'
import { Route as SurgicalGuideCreateRouteImport } from './routes/surgical-guide.create'
import { Route as SpecializedImplantsCategoryRouteImport } from './routes/specialized-implants.$category'
import { Route as ProfileAccountIdRouteImport } from './routes/profile.$accountId'
import { Route as ProductsProductIdRouteImport } from './routes/products.$productId'
import { Route as PatientsPatientIdRouteImport } from './routes/patients.$patientId'
import { Route as LabsStaffRouteImport } from './routes/labs.staff'
import { Route as LabsExploreRouteImport } from './routes/labs.explore'
import { Route as LabsDashboardRouteImport } from './routes/labs.dashboard'
import { Route as LabsCasesRouteImport } from './routes/labs.cases'
import { Route as LabsLabIdRouteImport } from './routes/labs.$labId'
import { Route as LabMyServicesRouteImport } from './routes/lab.my-services'
import { Route as ImplantsCountryRouteImport } from './routes/implants.$country'
import { Route as DoctorInvoicesInvoiceIdRouteImport } from './routes/doctor-invoices.$invoiceId'
import { Route as DesignerCaseIdRouteImport } from './routes/designer.$caseId'
import { Route as ClinicReportsRouteImport } from './routes/clinic.reports'
import { Route as ClinicOrdersRouteImport } from './routes/clinic.orders'
import { Route as ClinicMaterialsRouteImport } from './routes/clinic.materials'
import { Route as ClinicFinanceRouteImport } from './routes/clinic.finance'
import { Route as ClinicDoctorsRouteImport } from './routes/clinic.doctors'
import { Route as ClinicAppointmentsRouteImport } from './routes/clinic.appointments'
import { Route as BrandsBrandIdRouteImport } from './routes/brands.$brandId'
import { Route as AccountSettingsRouteImport } from './routes/account.settings'
import { Route as AccountHelpRouteImport } from './routes/account.help'
import { Route as AccountBalancesRouteImport } from './routes/account.balances'
import { Route as AccountAboutRouteImport } from './routes/account.about'
import { Route as SuppliesOfficeIdIndexRouteImport } from './routes/supplies.$officeId.index'
import { Route as SuppliesBranchBranchSlugRouteImport } from './routes/supplies.branch.$branchSlug'
import { Route as SuppliesOfficeIdBranchSlugRouteImport } from './routes/supplies.$officeId.$branchSlug'
import { Route as PatientsRxPatientIdRouteImport } from './routes/patients.rx.$patientId'
import { Route as LabsLabIdStatementRouteImport } from './routes/labs.$labId.statement'
import { Route as AccountHelpTopicSlugRouteImport } from './routes/account.help.topic.$slug'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportsRoute = ReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const QuickOrdersRoute = QuickOrdersRouteImport.update({
  id: '/quick-orders',
  path: '/quick-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductionRoute = ProductionRouteImport.update({
  id: '/production',
  path: '/production',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const OrdersRoute = OrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const OffersRoute = OffersRouteImport.update({
  id: '/offers',
  path: '/offers',
  getParentRoute: () => rootRouteImport,
} as any)
const MyAdsRoute = MyAdsRouteImport.update({
  id: '/my-ads',
  path: '/my-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const MoreRoute = MoreRouteImport.update({
  id: '/more',
  path: '/more',
  getParentRoute: () => rootRouteImport,
} as any)
const MessagesRoute = MessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceRoute = FinanceRouteImport.update({
  id: '/finance',
  path: '/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ExploreRoute = ExploreRouteImport.update({
  id: '/explore',
  path: '/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackCasesIndexRoute = TrackCasesIndexRouteImport.update({
  id: '/track-cases/',
  path: '/track-cases/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurgicalGuideIndexRoute = SurgicalGuideIndexRouteImport.update({
  id: '/surgical-guide/',
  path: '/surgical-guide/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliesIndexRoute = SuppliesIndexRouteImport.update({
  id: '/supplies/',
  path: '/supplies/',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecializedImplantsIndexRoute =
  SpecializedImplantsIndexRouteImport.update({
    id: '/specialized-implants/',
    path: '/specialized-implants/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientsIndexRoute = PatientsIndexRouteImport.update({
  id: '/patients/',
  path: '/patients/',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsIndexRoute = LabsIndexRouteImport.update({
  id: '/labs/',
  path: '/labs/',
  getParentRoute: () => rootRouteImport,
} as any)
const InvoicesIndexRoute = InvoicesIndexRouteImport.update({
  id: '/invoices/',
  path: '/invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantsIndexRoute = ImplantsIndexRouteImport.update({
  id: '/implants/',
  path: '/implants/',
  getParentRoute: () => rootRouteImport,
} as any)
const FavoritesIndexRoute = FavoritesIndexRouteImport.update({
  id: '/favorites/',
  path: '/favorites/',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorInvoicesIndexRoute = DoctorInvoicesIndexRouteImport.update({
  id: '/doctor-invoices/',
  path: '/doctor-invoices/',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerIndexRoute = DesignerIndexRouteImport.update({
  id: '/designer/',
  path: '/designer/',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicIndexRoute = ClinicIndexRouteImport.update({
  id: '/clinic/',
  path: '/clinic/',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsIndexRoute = BrandsIndexRouteImport.update({
  id: '/brands/',
  path: '/brands/',
  getParentRoute: () => rootRouteImport,
} as any)
const BoneGraftsIndexRoute = BoneGraftsIndexRouteImport.update({
  id: '/bone-grafts/',
  path: '/bone-grafts/',
  getParentRoute: () => rootRouteImport,
} as any)
const SurgicalGuideCreateRoute = SurgicalGuideCreateRouteImport.update({
  id: '/surgical-guide/create',
  path: '/surgical-guide/create',
  getParentRoute: () => rootRouteImport,
} as any)
const SpecializedImplantsCategoryRoute =
  SpecializedImplantsCategoryRouteImport.update({
    id: '/specialized-implants/$category',
    path: '/specialized-implants/$category',
    getParentRoute: () => rootRouteImport,
  } as any)
const ProfileAccountIdRoute = ProfileAccountIdRouteImport.update({
  id: '/profile/$accountId',
  path: '/profile/$accountId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsProductIdRoute = ProductsProductIdRouteImport.update({
  id: '/products/$productId',
  path: '/products/$productId',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientsPatientIdRoute = PatientsPatientIdRouteImport.update({
  id: '/patients/$patientId',
  path: '/patients/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsStaffRoute = LabsStaffRouteImport.update({
  id: '/labs/staff',
  path: '/labs/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsExploreRoute = LabsExploreRouteImport.update({
  id: '/labs/explore',
  path: '/labs/explore',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsDashboardRoute = LabsDashboardRouteImport.update({
  id: '/labs/dashboard',
  path: '/labs/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsCasesRoute = LabsCasesRouteImport.update({
  id: '/labs/cases',
  path: '/labs/cases',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsLabIdRoute = LabsLabIdRouteImport.update({
  id: '/labs/$labId',
  path: '/labs/$labId',
  getParentRoute: () => rootRouteImport,
} as any)
const LabMyServicesRoute = LabMyServicesRouteImport.update({
  id: '/lab/my-services',
  path: '/lab/my-services',
  getParentRoute: () => rootRouteImport,
} as any)
const ImplantsCountryRoute = ImplantsCountryRouteImport.update({
  id: '/implants/$country',
  path: '/implants/$country',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorInvoicesInvoiceIdRoute = DoctorInvoicesInvoiceIdRouteImport.update({
  id: '/doctor-invoices/$invoiceId',
  path: '/doctor-invoices/$invoiceId',
  getParentRoute: () => rootRouteImport,
} as any)
const DesignerCaseIdRoute = DesignerCaseIdRouteImport.update({
  id: '/designer/$caseId',
  path: '/designer/$caseId',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicReportsRoute = ClinicReportsRouteImport.update({
  id: '/clinic/reports',
  path: '/clinic/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicOrdersRoute = ClinicOrdersRouteImport.update({
  id: '/clinic/orders',
  path: '/clinic/orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicMaterialsRoute = ClinicMaterialsRouteImport.update({
  id: '/clinic/materials',
  path: '/clinic/materials',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicFinanceRoute = ClinicFinanceRouteImport.update({
  id: '/clinic/finance',
  path: '/clinic/finance',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicDoctorsRoute = ClinicDoctorsRouteImport.update({
  id: '/clinic/doctors',
  path: '/clinic/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const ClinicAppointmentsRoute = ClinicAppointmentsRouteImport.update({
  id: '/clinic/appointments',
  path: '/clinic/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const BrandsBrandIdRoute = BrandsBrandIdRouteImport.update({
  id: '/brands/$brandId',
  path: '/brands/$brandId',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountSettingsRoute = AccountSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AccountRoute,
} as any)
const AccountHelpRoute = AccountHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AccountRoute,
} as any)
const AccountBalancesRoute = AccountBalancesRouteImport.update({
  id: '/balances',
  path: '/balances',
  getParentRoute: () => AccountRoute,
} as any)
const AccountAboutRoute = AccountAboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => AccountRoute,
} as any)
const SuppliesOfficeIdIndexRoute = SuppliesOfficeIdIndexRouteImport.update({
  id: '/supplies/$officeId/',
  path: '/supplies/$officeId/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliesBranchBranchSlugRoute =
  SuppliesBranchBranchSlugRouteImport.update({
    id: '/supplies/branch/$branchSlug',
    path: '/supplies/branch/$branchSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const SuppliesOfficeIdBranchSlugRoute =
  SuppliesOfficeIdBranchSlugRouteImport.update({
    id: '/supplies/$officeId/$branchSlug',
    path: '/supplies/$officeId/$branchSlug',
    getParentRoute: () => rootRouteImport,
  } as any)
const PatientsRxPatientIdRoute = PatientsRxPatientIdRouteImport.update({
  id: '/patients/rx/$patientId',
  path: '/patients/rx/$patientId',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsLabIdStatementRoute = LabsLabIdStatementRouteImport.update({
  id: '/statement',
  path: '/statement',
  getParentRoute: () => LabsLabIdRoute,
} as any)
const AccountHelpTopicSlugRoute = AccountHelpTopicSlugRouteImport.update({
  id: '/topic/$slug',
  path: '/topic/$slug',
  getParentRoute: () => AccountHelpRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/doctors': typeof DoctorsRoute
  '/explore': typeof ExploreRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/my-ads': typeof MyAdsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/production': typeof ProductionRoute
  '/quick-orders': typeof QuickOrdersRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/account/about': typeof AccountAboutRoute
  '/account/balances': typeof AccountBalancesRoute
  '/account/help': typeof AccountHelpRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/clinic/appointments': typeof ClinicAppointmentsRoute
  '/clinic/doctors': typeof ClinicDoctorsRoute
  '/clinic/finance': typeof ClinicFinanceRoute
  '/clinic/materials': typeof ClinicMaterialsRoute
  '/clinic/orders': typeof ClinicOrdersRoute
  '/clinic/reports': typeof ClinicReportsRoute
  '/designer/$caseId': typeof DesignerCaseIdRoute
  '/doctor-invoices/$invoiceId': typeof DoctorInvoicesInvoiceIdRoute
  '/implants/$country': typeof ImplantsCountryRoute
  '/lab/my-services': typeof LabMyServicesRoute
  '/labs/$labId': typeof LabsLabIdRouteWithChildren
  '/labs/cases': typeof LabsCasesRoute
  '/labs/dashboard': typeof LabsDashboardRoute
  '/labs/explore': typeof LabsExploreRoute
  '/labs/staff': typeof LabsStaffRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/profile/$accountId': typeof ProfileAccountIdRoute
  '/specialized-implants/$category': typeof SpecializedImplantsCategoryRoute
  '/surgical-guide/create': typeof SurgicalGuideCreateRoute
  '/bone-grafts/': typeof BoneGraftsIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/clinic/': typeof ClinicIndexRoute
  '/designer/': typeof DesignerIndexRoute
  '/doctor-invoices/': typeof DoctorInvoicesIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/implants/': typeof ImplantsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/labs/': typeof LabsIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/specialized-implants/': typeof SpecializedImplantsIndexRoute
  '/supplies/': typeof SuppliesIndexRoute
  '/surgical-guide/': typeof SurgicalGuideIndexRoute
  '/track-cases/': typeof TrackCasesIndexRoute
  '/labs/$labId/statement': typeof LabsLabIdStatementRoute
  '/patients/rx/$patientId': typeof PatientsRxPatientIdRoute
  '/supplies/$officeId/$branchSlug': typeof SuppliesOfficeIdBranchSlugRoute
  '/supplies/branch/$branchSlug': typeof SuppliesBranchBranchSlugRoute
  '/supplies/$officeId/': typeof SuppliesOfficeIdIndexRoute
  '/account/help/topic/$slug': typeof AccountHelpTopicSlugRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/doctors': typeof DoctorsRoute
  '/explore': typeof ExploreRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/my-ads': typeof MyAdsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/production': typeof ProductionRoute
  '/quick-orders': typeof QuickOrdersRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/account/about': typeof AccountAboutRoute
  '/account/balances': typeof AccountBalancesRoute
  '/account/help': typeof AccountHelpRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/clinic/appointments': typeof ClinicAppointmentsRoute
  '/clinic/doctors': typeof ClinicDoctorsRoute
  '/clinic/finance': typeof ClinicFinanceRoute
  '/clinic/materials': typeof ClinicMaterialsRoute
  '/clinic/orders': typeof ClinicOrdersRoute
  '/clinic/reports': typeof ClinicReportsRoute
  '/designer/$caseId': typeof DesignerCaseIdRoute
  '/doctor-invoices/$invoiceId': typeof DoctorInvoicesInvoiceIdRoute
  '/implants/$country': typeof ImplantsCountryRoute
  '/lab/my-services': typeof LabMyServicesRoute
  '/labs/$labId': typeof LabsLabIdRouteWithChildren
  '/labs/cases': typeof LabsCasesRoute
  '/labs/dashboard': typeof LabsDashboardRoute
  '/labs/explore': typeof LabsExploreRoute
  '/labs/staff': typeof LabsStaffRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/profile/$accountId': typeof ProfileAccountIdRoute
  '/specialized-implants/$category': typeof SpecializedImplantsCategoryRoute
  '/surgical-guide/create': typeof SurgicalGuideCreateRoute
  '/bone-grafts': typeof BoneGraftsIndexRoute
  '/brands': typeof BrandsIndexRoute
  '/clinic': typeof ClinicIndexRoute
  '/designer': typeof DesignerIndexRoute
  '/doctor-invoices': typeof DoctorInvoicesIndexRoute
  '/favorites': typeof FavoritesIndexRoute
  '/implants': typeof ImplantsIndexRoute
  '/invoices': typeof InvoicesIndexRoute
  '/labs': typeof LabsIndexRoute
  '/patients': typeof PatientsIndexRoute
  '/specialized-implants': typeof SpecializedImplantsIndexRoute
  '/supplies': typeof SuppliesIndexRoute
  '/surgical-guide': typeof SurgicalGuideIndexRoute
  '/track-cases': typeof TrackCasesIndexRoute
  '/labs/$labId/statement': typeof LabsLabIdStatementRoute
  '/patients/rx/$patientId': typeof PatientsRxPatientIdRoute
  '/supplies/$officeId/$branchSlug': typeof SuppliesOfficeIdBranchSlugRoute
  '/supplies/branch/$branchSlug': typeof SuppliesBranchBranchSlugRoute
  '/supplies/$officeId': typeof SuppliesOfficeIdIndexRoute
  '/account/help/topic/$slug': typeof AccountHelpTopicSlugRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRouteWithChildren
  '/admin': typeof AdminRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof DashboardRoute
  '/doctors': typeof DoctorsRoute
  '/explore': typeof ExploreRoute
  '/finance': typeof FinanceRoute
  '/login': typeof LoginRoute
  '/messages': typeof MessagesRoute
  '/more': typeof MoreRoute
  '/my-ads': typeof MyAdsRoute
  '/offers': typeof OffersRoute
  '/orders': typeof OrdersRoute
  '/pricing': typeof PricingRoute
  '/production': typeof ProductionRoute
  '/quick-orders': typeof QuickOrdersRoute
  '/register': typeof RegisterRoute
  '/reports': typeof ReportsRoute
  '/signup': typeof SignupRoute
  '/account/about': typeof AccountAboutRoute
  '/account/balances': typeof AccountBalancesRoute
  '/account/help': typeof AccountHelpRouteWithChildren
  '/account/settings': typeof AccountSettingsRoute
  '/brands/$brandId': typeof BrandsBrandIdRoute
  '/clinic/appointments': typeof ClinicAppointmentsRoute
  '/clinic/doctors': typeof ClinicDoctorsRoute
  '/clinic/finance': typeof ClinicFinanceRoute
  '/clinic/materials': typeof ClinicMaterialsRoute
  '/clinic/orders': typeof ClinicOrdersRoute
  '/clinic/reports': typeof ClinicReportsRoute
  '/designer/$caseId': typeof DesignerCaseIdRoute
  '/doctor-invoices/$invoiceId': typeof DoctorInvoicesInvoiceIdRoute
  '/implants/$country': typeof ImplantsCountryRoute
  '/lab/my-services': typeof LabMyServicesRoute
  '/labs/$labId': typeof LabsLabIdRouteWithChildren
  '/labs/cases': typeof LabsCasesRoute
  '/labs/dashboard': typeof LabsDashboardRoute
  '/labs/explore': typeof LabsExploreRoute
  '/labs/staff': typeof LabsStaffRoute
  '/patients/$patientId': typeof PatientsPatientIdRoute
  '/products/$productId': typeof ProductsProductIdRoute
  '/profile/$accountId': typeof ProfileAccountIdRoute
  '/specialized-implants/$category': typeof SpecializedImplantsCategoryRoute
  '/surgical-guide/create': typeof SurgicalGuideCreateRoute
  '/bone-grafts/': typeof BoneGraftsIndexRoute
  '/brands/': typeof BrandsIndexRoute
  '/clinic/': typeof ClinicIndexRoute
  '/designer/': typeof DesignerIndexRoute
  '/doctor-invoices/': typeof DoctorInvoicesIndexRoute
  '/favorites/': typeof FavoritesIndexRoute
  '/implants/': typeof ImplantsIndexRoute
  '/invoices/': typeof InvoicesIndexRoute
  '/labs/': typeof LabsIndexRoute
  '/patients/': typeof PatientsIndexRoute
  '/specialized-implants/': typeof SpecializedImplantsIndexRoute
  '/supplies/': typeof SuppliesIndexRoute
  '/surgical-guide/': typeof SurgicalGuideIndexRoute
  '/track-cases/': typeof TrackCasesIndexRoute
  '/labs/$labId/statement': typeof LabsLabIdStatementRoute
  '/patients/rx/$patientId': typeof PatientsRxPatientIdRoute
  '/supplies/$officeId/$branchSlug': typeof SuppliesOfficeIdBranchSlugRoute
  '/supplies/branch/$branchSlug': typeof SuppliesBranchBranchSlugRoute
  '/supplies/$officeId/': typeof SuppliesOfficeIdIndexRoute
  '/account/help/topic/$slug': typeof AccountHelpTopicSlugRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/doctors'
    | '/explore'
    | '/finance'
    | '/login'
    | '/messages'
    | '/more'
    | '/my-ads'
    | '/offers'
    | '/orders'
    | '/pricing'
    | '/production'
    | '/quick-orders'
    | '/register'
    | '/reports'
    | '/signup'
    | '/account/about'
    | '/account/balances'
    | '/account/help'
    | '/account/settings'
    | '/brands/$brandId'
    | '/clinic/appointments'
    | '/clinic/doctors'
    | '/clinic/finance'
    | '/clinic/materials'
    | '/clinic/orders'
    | '/clinic/reports'
    | '/designer/$caseId'
    | '/doctor-invoices/$invoiceId'
    | '/implants/$country'
    | '/lab/my-services'
    | '/labs/$labId'
    | '/labs/cases'
    | '/labs/dashboard'
    | '/labs/explore'
    | '/labs/staff'
    | '/patients/$patientId'
    | '/products/$productId'
    | '/profile/$accountId'
    | '/specialized-implants/$category'
    | '/surgical-guide/create'
    | '/bone-grafts/'
    | '/brands/'
    | '/clinic/'
    | '/designer/'
    | '/doctor-invoices/'
    | '/favorites/'
    | '/implants/'
    | '/invoices/'
    | '/labs/'
    | '/patients/'
    | '/specialized-implants/'
    | '/supplies/'
    | '/surgical-guide/'
    | '/track-cases/'
    | '/labs/$labId/statement'
    | '/patients/rx/$patientId'
    | '/supplies/$officeId/$branchSlug'
    | '/supplies/branch/$branchSlug'
    | '/supplies/$officeId/'
    | '/account/help/topic/$slug'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/doctors'
    | '/explore'
    | '/finance'
    | '/login'
    | '/messages'
    | '/more'
    | '/my-ads'
    | '/offers'
    | '/orders'
    | '/pricing'
    | '/production'
    | '/quick-orders'
    | '/register'
    | '/reports'
    | '/signup'
    | '/account/about'
    | '/account/balances'
    | '/account/help'
    | '/account/settings'
    | '/brands/$brandId'
    | '/clinic/appointments'
    | '/clinic/doctors'
    | '/clinic/finance'
    | '/clinic/materials'
    | '/clinic/orders'
    | '/clinic/reports'
    | '/designer/$caseId'
    | '/doctor-invoices/$invoiceId'
    | '/implants/$country'
    | '/lab/my-services'
    | '/labs/$labId'
    | '/labs/cases'
    | '/labs/dashboard'
    | '/labs/explore'
    | '/labs/staff'
    | '/patients/$patientId'
    | '/products/$productId'
    | '/profile/$accountId'
    | '/specialized-implants/$category'
    | '/surgical-guide/create'
    | '/bone-grafts'
    | '/brands'
    | '/clinic'
    | '/designer'
    | '/doctor-invoices'
    | '/favorites'
    | '/implants'
    | '/invoices'
    | '/labs'
    | '/patients'
    | '/specialized-implants'
    | '/supplies'
    | '/surgical-guide'
    | '/track-cases'
    | '/labs/$labId/statement'
    | '/patients/rx/$patientId'
    | '/supplies/$officeId/$branchSlug'
    | '/supplies/branch/$branchSlug'
    | '/supplies/$officeId'
    | '/account/help/topic/$slug'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/auth'
    | '/dashboard'
    | '/doctors'
    | '/explore'
    | '/finance'
    | '/login'
    | '/messages'
    | '/more'
    | '/my-ads'
    | '/offers'
    | '/orders'
    | '/pricing'
    | '/production'
    | '/quick-orders'
    | '/register'
    | '/reports'
    | '/signup'
    | '/account/about'
    | '/account/balances'
    | '/account/help'
    | '/account/settings'
    | '/brands/$brandId'
    | '/clinic/appointments'
    | '/clinic/doctors'
    | '/clinic/finance'
    | '/clinic/materials'
    | '/clinic/orders'
    | '/clinic/reports'
    | '/designer/$caseId'
    | '/doctor-invoices/$invoiceId'
    | '/implants/$country'
    | '/lab/my-services'
    | '/labs/$labId'
    | '/labs/cases'
    | '/labs/dashboard'
    | '/labs/explore'
    | '/labs/staff'
    | '/patients/$patientId'
    | '/products/$productId'
    | '/profile/$accountId'
    | '/specialized-implants/$category'
    | '/surgical-guide/create'
    | '/bone-grafts/'
    | '/brands/'
    | '/clinic/'
    | '/designer/'
    | '/doctor-invoices/'
    | '/favorites/'
    | '/implants/'
    | '/invoices/'
    | '/labs/'
    | '/patients/'
    | '/specialized-implants/'
    | '/supplies/'
    | '/surgical-guide/'
    | '/track-cases/'
    | '/labs/$labId/statement'
    | '/patients/rx/$patientId'
    | '/supplies/$officeId/$branchSlug'
    | '/supplies/branch/$branchSlug'
    | '/supplies/$officeId/'
    | '/account/help/topic/$slug'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRouteWithChildren
  AdminRoute: typeof AdminRoute
  AuthRoute: typeof AuthRoute
  DashboardRoute: typeof DashboardRoute
  DoctorsRoute: typeof DoctorsRoute
  ExploreRoute: typeof ExploreRoute
  FinanceRoute: typeof FinanceRoute
  LoginRoute: typeof LoginRoute
  MessagesRoute: typeof MessagesRoute
  MoreRoute: typeof MoreRoute
  MyAdsRoute: typeof MyAdsRoute
  OffersRoute: typeof OffersRoute
  OrdersRoute: typeof OrdersRoute
  PricingRoute: typeof PricingRoute
  ProductionRoute: typeof ProductionRoute
  QuickOrdersRoute: typeof QuickOrdersRoute
  RegisterRoute: typeof RegisterRoute
  ReportsRoute: typeof ReportsRoute
  SignupRoute: typeof SignupRoute
  BrandsBrandIdRoute: typeof BrandsBrandIdRoute
  ClinicAppointmentsRoute: typeof ClinicAppointmentsRoute
  ClinicDoctorsRoute: typeof ClinicDoctorsRoute
  ClinicFinanceRoute: typeof ClinicFinanceRoute
  ClinicMaterialsRoute: typeof ClinicMaterialsRoute
  ClinicOrdersRoute: typeof ClinicOrdersRoute
  ClinicReportsRoute: typeof ClinicReportsRoute
  DesignerCaseIdRoute: typeof DesignerCaseIdRoute
  DoctorInvoicesInvoiceIdRoute: typeof DoctorInvoicesInvoiceIdRoute
  ImplantsCountryRoute: typeof ImplantsCountryRoute
  LabMyServicesRoute: typeof LabMyServicesRoute
  LabsLabIdRoute: typeof LabsLabIdRouteWithChildren
  LabsCasesRoute: typeof LabsCasesRoute
  LabsDashboardRoute: typeof LabsDashboardRoute
  LabsExploreRoute: typeof LabsExploreRoute
  LabsStaffRoute: typeof LabsStaffRoute
  PatientsPatientIdRoute: typeof PatientsPatientIdRoute
  ProductsProductIdRoute: typeof ProductsProductIdRoute
  ProfileAccountIdRoute: typeof ProfileAccountIdRoute
  SpecializedImplantsCategoryRoute: typeof SpecializedImplantsCategoryRoute
  SurgicalGuideCreateRoute: typeof SurgicalGuideCreateRoute
  BoneGraftsIndexRoute: typeof BoneGraftsIndexRoute
  BrandsIndexRoute: typeof BrandsIndexRoute
  ClinicIndexRoute: typeof ClinicIndexRoute
  DesignerIndexRoute: typeof DesignerIndexRoute
  DoctorInvoicesIndexRoute: typeof DoctorInvoicesIndexRoute
  FavoritesIndexRoute: typeof FavoritesIndexRoute
  ImplantsIndexRoute: typeof ImplantsIndexRoute
  InvoicesIndexRoute: typeof InvoicesIndexRoute
  LabsIndexRoute: typeof LabsIndexRoute
  PatientsIndexRoute: typeof PatientsIndexRoute
  SpecializedImplantsIndexRoute: typeof SpecializedImplantsIndexRoute
  SuppliesIndexRoute: typeof SuppliesIndexRoute
  SurgicalGuideIndexRoute: typeof SurgicalGuideIndexRoute
  TrackCasesIndexRoute: typeof TrackCasesIndexRoute
  PatientsRxPatientIdRoute: typeof PatientsRxPatientIdRoute
  SuppliesOfficeIdBranchSlugRoute: typeof SuppliesOfficeIdBranchSlugRoute
  SuppliesBranchBranchSlugRoute: typeof SuppliesBranchBranchSlugRoute
  SuppliesOfficeIdIndexRoute: typeof SuppliesOfficeIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reports': {
      id: '/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof ReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quick-orders': {
      id: '/quick-orders'
      path: '/quick-orders'
      fullPath: '/quick-orders'
      preLoaderRoute: typeof QuickOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/production': {
      id: '/production'
      path: '/production'
      fullPath: '/production'
      preLoaderRoute: typeof ProductionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/orders': {
      id: '/orders'
      path: '/orders'
      fullPath: '/orders'
      preLoaderRoute: typeof OrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/offers': {
      id: '/offers'
      path: '/offers'
      fullPath: '/offers'
      preLoaderRoute: typeof OffersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-ads': {
      id: '/my-ads'
      path: '/my-ads'
      fullPath: '/my-ads'
      preLoaderRoute: typeof MyAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/more': {
      id: '/more'
      path: '/more'
      fullPath: '/more'
      preLoaderRoute: typeof MoreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/messages': {
      id: '/messages'
      path: '/messages'
      fullPath: '/messages'
      preLoaderRoute: typeof MessagesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/finance': {
      id: '/finance'
      path: '/finance'
      fullPath: '/finance'
      preLoaderRoute: typeof FinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/explore': {
      id: '/explore'
      path: '/explore'
      fullPath: '/explore'
      preLoaderRoute: typeof ExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track-cases/': {
      id: '/track-cases/'
      path: '/track-cases'
      fullPath: '/track-cases/'
      preLoaderRoute: typeof TrackCasesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surgical-guide/': {
      id: '/surgical-guide/'
      path: '/surgical-guide'
      fullPath: '/surgical-guide/'
      preLoaderRoute: typeof SurgicalGuideIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplies/': {
      id: '/supplies/'
      path: '/supplies'
      fullPath: '/supplies/'
      preLoaderRoute: typeof SuppliesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialized-implants/': {
      id: '/specialized-implants/'
      path: '/specialized-implants'
      fullPath: '/specialized-implants/'
      preLoaderRoute: typeof SpecializedImplantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/': {
      id: '/patients/'
      path: '/patients'
      fullPath: '/patients/'
      preLoaderRoute: typeof PatientsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/': {
      id: '/labs/'
      path: '/labs'
      fullPath: '/labs/'
      preLoaderRoute: typeof LabsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invoices/': {
      id: '/invoices/'
      path: '/invoices'
      fullPath: '/invoices/'
      preLoaderRoute: typeof InvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implants/': {
      id: '/implants/'
      path: '/implants'
      fullPath: '/implants/'
      preLoaderRoute: typeof ImplantsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/favorites/': {
      id: '/favorites/'
      path: '/favorites'
      fullPath: '/favorites/'
      preLoaderRoute: typeof FavoritesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-invoices/': {
      id: '/doctor-invoices/'
      path: '/doctor-invoices'
      fullPath: '/doctor-invoices/'
      preLoaderRoute: typeof DoctorInvoicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer/': {
      id: '/designer/'
      path: '/designer'
      fullPath: '/designer/'
      preLoaderRoute: typeof DesignerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/': {
      id: '/clinic/'
      path: '/clinic'
      fullPath: '/clinic/'
      preLoaderRoute: typeof ClinicIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/': {
      id: '/brands/'
      path: '/brands'
      fullPath: '/brands/'
      preLoaderRoute: typeof BrandsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bone-grafts/': {
      id: '/bone-grafts/'
      path: '/bone-grafts'
      fullPath: '/bone-grafts/'
      preLoaderRoute: typeof BoneGraftsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/surgical-guide/create': {
      id: '/surgical-guide/create'
      path: '/surgical-guide/create'
      fullPath: '/surgical-guide/create'
      preLoaderRoute: typeof SurgicalGuideCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/specialized-implants/$category': {
      id: '/specialized-implants/$category'
      path: '/specialized-implants/$category'
      fullPath: '/specialized-implants/$category'
      preLoaderRoute: typeof SpecializedImplantsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/$accountId': {
      id: '/profile/$accountId'
      path: '/profile/$accountId'
      fullPath: '/profile/$accountId'
      preLoaderRoute: typeof ProfileAccountIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$productId': {
      id: '/products/$productId'
      path: '/products/$productId'
      fullPath: '/products/$productId'
      preLoaderRoute: typeof ProductsProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/$patientId': {
      id: '/patients/$patientId'
      path: '/patients/$patientId'
      fullPath: '/patients/$patientId'
      preLoaderRoute: typeof PatientsPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/staff': {
      id: '/labs/staff'
      path: '/labs/staff'
      fullPath: '/labs/staff'
      preLoaderRoute: typeof LabsStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/explore': {
      id: '/labs/explore'
      path: '/labs/explore'
      fullPath: '/labs/explore'
      preLoaderRoute: typeof LabsExploreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/dashboard': {
      id: '/labs/dashboard'
      path: '/labs/dashboard'
      fullPath: '/labs/dashboard'
      preLoaderRoute: typeof LabsDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/cases': {
      id: '/labs/cases'
      path: '/labs/cases'
      fullPath: '/labs/cases'
      preLoaderRoute: typeof LabsCasesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/$labId': {
      id: '/labs/$labId'
      path: '/labs/$labId'
      fullPath: '/labs/$labId'
      preLoaderRoute: typeof LabsLabIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab/my-services': {
      id: '/lab/my-services'
      path: '/lab/my-services'
      fullPath: '/lab/my-services'
      preLoaderRoute: typeof LabMyServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/implants/$country': {
      id: '/implants/$country'
      path: '/implants/$country'
      fullPath: '/implants/$country'
      preLoaderRoute: typeof ImplantsCountryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-invoices/$invoiceId': {
      id: '/doctor-invoices/$invoiceId'
      path: '/doctor-invoices/$invoiceId'
      fullPath: '/doctor-invoices/$invoiceId'
      preLoaderRoute: typeof DoctorInvoicesInvoiceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/designer/$caseId': {
      id: '/designer/$caseId'
      path: '/designer/$caseId'
      fullPath: '/designer/$caseId'
      preLoaderRoute: typeof DesignerCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/reports': {
      id: '/clinic/reports'
      path: '/clinic/reports'
      fullPath: '/clinic/reports'
      preLoaderRoute: typeof ClinicReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/orders': {
      id: '/clinic/orders'
      path: '/clinic/orders'
      fullPath: '/clinic/orders'
      preLoaderRoute: typeof ClinicOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/materials': {
      id: '/clinic/materials'
      path: '/clinic/materials'
      fullPath: '/clinic/materials'
      preLoaderRoute: typeof ClinicMaterialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/finance': {
      id: '/clinic/finance'
      path: '/clinic/finance'
      fullPath: '/clinic/finance'
      preLoaderRoute: typeof ClinicFinanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/doctors': {
      id: '/clinic/doctors'
      path: '/clinic/doctors'
      fullPath: '/clinic/doctors'
      preLoaderRoute: typeof ClinicDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clinic/appointments': {
      id: '/clinic/appointments'
      path: '/clinic/appointments'
      fullPath: '/clinic/appointments'
      preLoaderRoute: typeof ClinicAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brands/$brandId': {
      id: '/brands/$brandId'
      path: '/brands/$brandId'
      fullPath: '/brands/$brandId'
      preLoaderRoute: typeof BrandsBrandIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account/settings': {
      id: '/account/settings'
      path: '/settings'
      fullPath: '/account/settings'
      preLoaderRoute: typeof AccountSettingsRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/help': {
      id: '/account/help'
      path: '/help'
      fullPath: '/account/help'
      preLoaderRoute: typeof AccountHelpRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/balances': {
      id: '/account/balances'
      path: '/balances'
      fullPath: '/account/balances'
      preLoaderRoute: typeof AccountBalancesRouteImport
      parentRoute: typeof AccountRoute
    }
    '/account/about': {
      id: '/account/about'
      path: '/about'
      fullPath: '/account/about'
      preLoaderRoute: typeof AccountAboutRouteImport
      parentRoute: typeof AccountRoute
    }
    '/supplies/$officeId/': {
      id: '/supplies/$officeId/'
      path: '/supplies/$officeId'
      fullPath: '/supplies/$officeId/'
      preLoaderRoute: typeof SuppliesOfficeIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplies/branch/$branchSlug': {
      id: '/supplies/branch/$branchSlug'
      path: '/supplies/branch/$branchSlug'
      fullPath: '/supplies/branch/$branchSlug'
      preLoaderRoute: typeof SuppliesBranchBranchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplies/$officeId/$branchSlug': {
      id: '/supplies/$officeId/$branchSlug'
      path: '/supplies/$officeId/$branchSlug'
      fullPath: '/supplies/$officeId/$branchSlug'
      preLoaderRoute: typeof SuppliesOfficeIdBranchSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patients/rx/$patientId': {
      id: '/patients/rx/$patientId'
      path: '/patients/rx/$patientId'
      fullPath: '/patients/rx/$patientId'
      preLoaderRoute: typeof PatientsRxPatientIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs/$labId/statement': {
      id: '/labs/$labId/statement'
      path: '/statement'
      fullPath: '/labs/$labId/statement'
      preLoaderRoute: typeof LabsLabIdStatementRouteImport
      parentRoute: typeof LabsLabIdRoute
    }
    '/account/help/topic/$slug': {
      id: '/account/help/topic/$slug'
      path: '/topic/$slug'
      fullPath: '/account/help/topic/$slug'
      preLoaderRoute: typeof AccountHelpTopicSlugRouteImport
      parentRoute: typeof AccountHelpRoute
    }
  }
}

interface AccountHelpRouteChildren {
  AccountHelpTopicSlugRoute: typeof AccountHelpTopicSlugRoute
}

const AccountHelpRouteChildren: AccountHelpRouteChildren = {
  AccountHelpTopicSlugRoute: AccountHelpTopicSlugRoute,
}

const AccountHelpRouteWithChildren = AccountHelpRoute._addFileChildren(
  AccountHelpRouteChildren,
)

interface AccountRouteChildren {
  AccountAboutRoute: typeof AccountAboutRoute
  AccountBalancesRoute: typeof AccountBalancesRoute
  AccountHelpRoute: typeof AccountHelpRouteWithChildren
  AccountSettingsRoute: typeof AccountSettingsRoute
}

const AccountRouteChildren: AccountRouteChildren = {
  AccountAboutRoute: AccountAboutRoute,
  AccountBalancesRoute: AccountBalancesRoute,
  AccountHelpRoute: AccountHelpRouteWithChildren,
  AccountSettingsRoute: AccountSettingsRoute,
}

const AccountRouteWithChildren =
  AccountRoute._addFileChildren(AccountRouteChildren)

interface LabsLabIdRouteChildren {
  LabsLabIdStatementRoute: typeof LabsLabIdStatementRoute
}

const LabsLabIdRouteChildren: LabsLabIdRouteChildren = {
  LabsLabIdStatementRoute: LabsLabIdStatementRoute,
}

const LabsLabIdRouteWithChildren = LabsLabIdRoute._addFileChildren(
  LabsLabIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRouteWithChildren,
  AdminRoute: AdminRoute,
  AuthRoute: AuthRoute,
  DashboardRoute: DashboardRoute,
  DoctorsRoute: DoctorsRoute,
  ExploreRoute: ExploreRoute,
  FinanceRoute: FinanceRoute,
  LoginRoute: LoginRoute,
  MessagesRoute: MessagesRoute,
  MoreRoute: MoreRoute,
  MyAdsRoute: MyAdsRoute,
  OffersRoute: OffersRoute,
  OrdersRoute: OrdersRoute,
  PricingRoute: PricingRoute,
  ProductionRoute: ProductionRoute,
  QuickOrdersRoute: QuickOrdersRoute,
  RegisterRoute: RegisterRoute,
  ReportsRoute: ReportsRoute,
  SignupRoute: SignupRoute,
  BrandsBrandIdRoute: BrandsBrandIdRoute,
  ClinicAppointmentsRoute: ClinicAppointmentsRoute,
  ClinicDoctorsRoute: ClinicDoctorsRoute,
  ClinicFinanceRoute: ClinicFinanceRoute,
  ClinicMaterialsRoute: ClinicMaterialsRoute,
  ClinicOrdersRoute: ClinicOrdersRoute,
  ClinicReportsRoute: ClinicReportsRoute,
  DesignerCaseIdRoute: DesignerCaseIdRoute,
  DoctorInvoicesInvoiceIdRoute: DoctorInvoicesInvoiceIdRoute,
  ImplantsCountryRoute: ImplantsCountryRoute,
  LabMyServicesRoute: LabMyServicesRoute,
  LabsLabIdRoute: LabsLabIdRouteWithChildren,
  LabsCasesRoute: LabsCasesRoute,
  LabsDashboardRoute: LabsDashboardRoute,
  LabsExploreRoute: LabsExploreRoute,
  LabsStaffRoute: LabsStaffRoute,
  PatientsPatientIdRoute: PatientsPatientIdRoute,
  ProductsProductIdRoute: ProductsProductIdRoute,
  ProfileAccountIdRoute: ProfileAccountIdRoute,
  SpecializedImplantsCategoryRoute: SpecializedImplantsCategoryRoute,
  SurgicalGuideCreateRoute: SurgicalGuideCreateRoute,
  BoneGraftsIndexRoute: BoneGraftsIndexRoute,
  BrandsIndexRoute: BrandsIndexRoute,
  ClinicIndexRoute: ClinicIndexRoute,
  DesignerIndexRoute: DesignerIndexRoute,
  DoctorInvoicesIndexRoute: DoctorInvoicesIndexRoute,
  FavoritesIndexRoute: FavoritesIndexRoute,
  ImplantsIndexRoute: ImplantsIndexRoute,
  InvoicesIndexRoute: InvoicesIndexRoute,
  LabsIndexRoute: LabsIndexRoute,
  PatientsIndexRoute: PatientsIndexRoute,
  SpecializedImplantsIndexRoute: SpecializedImplantsIndexRoute,
  SuppliesIndexRoute: SuppliesIndexRoute,
  SurgicalGuideIndexRoute: SurgicalGuideIndexRoute,
  TrackCasesIndexRoute: TrackCasesIndexRoute,
  PatientsRxPatientIdRoute: PatientsRxPatientIdRoute,
  SuppliesOfficeIdBranchSlugRoute: SuppliesOfficeIdBranchSlugRoute,
  SuppliesBranchBranchSlugRoute: SuppliesBranchBranchSlugRoute,
  SuppliesOfficeIdIndexRoute: SuppliesOfficeIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
